name: Update Steam Stats

on:
    schedule:
        - cron: "0 2 * * *" # 每天凌晨2点更新（避免与WakaTime冲突）
    workflow_dispatch:

jobs:
    update-stats:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.9"

            - name: Install dependencies
              run: |
                  pip install requests matplotlib

            - name: Generate Steam Chart
              env:
                  STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
                  STEAM_ID: ${{ secrets.STEAM_ID }}
              run: |
                  echo "Starting Steam chart generation..."
                  if [ -z "$STEAM_API_KEY" ] || [ -z "$STEAM_ID" ]; then
                    echo "Steam credentials not found, skipping Steam chart generation."
                    exit 0
                  else
                    echo "Using Steam API credentials..."
                    python scripts/generate_steam_chart.py
                    echo "Chart generation completed."
                    echo "Checking generated files:"
                    ls -la steam_stats*.svg || echo "No SVG files found"
                  fi

            - name: Commit changes
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add -A
                  if ! git diff --staged --quiet; then
                    git commit -m "Update Steam stats"
                    git push
                  else
                    echo "No changes to commit"
                  fi
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
